import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const stackDirectory = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const generatedDirectory = resolve(stackDirectory, 'generated');
const outputFile = resolve(generatedDirectory, 'example.txt');

mkdirSync(generatedDirectory, { recursive: true });
writeFileSync(outputFile, 'Generated by ProducerStack build hook.\n');

console.log(`Wrote ${outputFile}`);