import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { input, select } from '@inquirer/prompts';
import { STACKS } from '../config/stacks';
import { runPrompt } from './prompt';

const usage = `Scaffold an optional build hook for a root source area or stack.

Usage:
	pnpm scaffold:build-script
	pnpm scaffold:build-script -- source <root-directory>
	pnpm scaffold:build-script -- stack <stack-id>
`;
const arguments_ = process.argv.slice(2).filter((argument) => argument !== '--');

if (arguments_.includes('--help')) {
    console.log(usage);
    process.exit(0);
}

type Target =
    | { readonly kind: 'source'; readonly directory: string }
    | { readonly kind: 'stack'; readonly id: string; readonly directory: string };

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const reservedRootDirectories = new Set(['stacks', 'scripts', 'node_modules', 'cdk.out']);

const validateSourceDirectory = (directory: string): true | string => {
    if (!/^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/.test(directory)) {
        return 'Use a lowercase kebab-case root directory name.';
    }
    if (reservedRootDirectories.has(directory)) {
        return `${directory} cannot be used as a source area.`;
    }
    return true;
};

const stackTarget = (id: string): Target => {
    const stack = STACKS.find((candidate) => candidate.id === id);
    const stackPath = stack?.paths.find((path) => /^stacks\/[^/]+\/$/.test(path));
    if (!stack || !stackPath) {
        throw new Error(`Unknown stack "${id}". Known stacks: ${STACKS.map((stack) => stack.id).join(', ')}.`);
    }
    return { kind: 'stack', id: stack.id, directory: stackPath.replace(/\/$/, '') };
};

const targetFromArguments = (): Target | undefined => {
    if (arguments_.length === 0) {
        return undefined;
    }
    if (arguments_.length !== 2) {
        throw new Error(usage);
    }

    const [kind, name] = arguments_;
    if (kind === 'source') {
        const validation = validateSourceDirectory(name);
        if (validation !== true) {
            throw new Error(validation);
        }
        return { kind, directory: name };
    }
    if (kind === 'stack') {
        return stackTarget(name);
    }
    throw new Error(`Unknown target type "${kind}". Use "source" or "stack".\n\n${usage}`);
};

const promptForTarget = async (): Promise<Target> => {
    const selection = await runPrompt(() =>
        select({
            message: 'Where should the build hook be added?',
            choices: [
                { value: 'source', name: 'Root source area' },
                ...STACKS.map((stack) => ({
                    value: stack.id,
                    name: stack.id,
                    description: stack.description,
                })),
            ],
        }),
    );
    if (selection !== 'source') {
        return stackTarget(selection);
    }

    const directory = await runPrompt(() =>
        input({
            message: 'Root source directory:',
            validate: validateSourceDirectory,
        }),
    );
    return { kind: 'source', directory };
};

const target = targetFromArguments() ?? (await promptForTarget());
const scriptsDirectory = resolve(repoRoot, target.directory, 'scripts');
const scriptPath = resolve(scriptsDirectory, 'build.ts');
if (existsSync(scriptPath)) {
    throw new Error(`Build hook already exists: ${target.directory}/scripts/build.ts`);
}

const scriptSource = `import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ownerDirectory = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const generatedDirectory = resolve(ownerDirectory, 'generated');

mkdirSync(generatedDirectory, { recursive: true });
writeFileSync(
	resolve(generatedDirectory, 'example.txt'),
	'Generated by ${target.kind === 'stack' ? target.id : target.directory} build hook.\\n',
);

console.log('Wrote ' + resolve(generatedDirectory, 'example.txt'));
`;

mkdirSync(scriptsDirectory, { recursive: true });
writeFileSync(scriptPath, scriptSource, { flag: 'wx' });

console.log(`Created ${target.directory}/scripts/build.ts`);
console.log(
    target.kind === 'stack'
        ? `Run: pnpm build -- ${target.id}`
        : `Run: pnpm build -- ${target.directory}`,
);